# Exercise 1 

In this exercise, we will go over an object-oriented programming exercises related to standard operations with `pandas` data frames. 

### Exercise 1(a) (10 points)

Create a class called `DataFrameProcessor` that will handle basic operations on a pandas DataFrame. Your class should:

1. Initialize with a pandas DataFrame.
2. Have a method get_column_stats(column_name) that returns the mean, median, and standard deviation of the specified column.
3. Have a method filter_rows(column_name, threshold) that returns a new DataFrame with rows where the values in the specified column are greater than the given threshold.
4. Have a method add_new_column(column_name, data) that adds a new column with the specified name and data to the DataFrame.

In [109]:
class DataFrameProcessor:
    def __init__(self, dataframe):
        """Initialize the DataFrameProcessor with a pandas Dataframe."""
        self.dataframe = dataframe

    def get_column_stats(self, column_name):
        """Return the mean, median, and std deviation of the specified column."""
        col = self.dataframe[column_name]
        return {
            'mean': col.mean(),
            'median': col.median(),
            'std': col.std()
        }

    def filter_rows(self, column_name, threshold):
        """Return a Datafram with rows where hte specified column's value is greater than the threshold."""
        return self.dataframe[self.dataframe[column_name] > threshold]

    def add_new_column(self, column_name, data):
        """Add a new column to the dataframe with the specified data."""
        self.dataframe[column_name] = data
        return self.df

### Exercise 1(b) (3 points)

Create a data frame called `df` with three columns and 20 rows. Fill the data frame with random integers from 1 to 20. Hint: use `np.random.randint` from `numpy` to generate the random integers.

In [110]:
import pandas as pd
import numpy as np 

df = pd.DataFrame(np.random.randint(1, 21, size=(20, 3)),
                  columns=['col_1', 'col_2', 'col_3'])
df

    col_1  col_2  col_3
0       2     15      8
1       8     17     12
2      19     10      9
3       5      6     20
4       2     13      6
5       5      1      6
6       6     16      4
7      11      9      3
8      19      8      5
9       4      6      2
10     20     11      4
11     15      6     17
12      6     19      2
13     15     11      8
14     19     13     12
15      5      6      4
16     19     20      1
17     20     17     12
18     15      1     14
19      6      5     11

### Exercise 1(c) (4 points)

Using the `DataFrameProcessor` class, report the stats for each of the columns in `df`.

In [111]:
#Initializaing Dataframe Process wiht the created Dataframe
df_processor = DataFrameProcessor(df)

#Reporting the statistics for each of the columns.
for col in df.columns:
    print(f'Processing column: {col}"')
    stats = processor.get_column_stats(col)
    print(f"{col}: mean = {stats['mean']:.2f}, "
          f"median = {stats['median']:.2f}, std = {stats['std']:.2f}")

Processing column: col_1"
col_1: mean = 7.40, median = 8.00, std = 4.79
Processing column: col_2"
col_2: mean = 9.40, median = 8.50, std = 5.50
Processing column: col_3"
col_3: mean = 11.05, median = 12.50, std = 5.21

### Exercise 1(d) (3 points)

Filter the rows where `col_3` is greater than 12.

In [112]:
filtered_df = df_processor.filter_rows('col_3', 12)
filtered_df

    col_1  col_2  col_3
3       5      6     20
11     15      6     17
18     15      1     14

### Exercise 1(e) (3 points)

Create a list with random intergers from 1 to 20. Add the list to `df` as new column called `col_4`.

In [116]:
df['col_4'] = np.random.randint(1, 21, size=len(df))
df_processor.add_new_column
df.head(-1)

    col_1  col_2  col_3  col_4
0       2     15      8     15
1       8     17     12      1
2      19     10      9     17
3       5      6     20      1
4       2     13      6     15
5       5      1      6      2
6       6     16      4     14
7      11      9      3      8
8      19      8      5      8
9       4      6      2     19
10     20     11      4      7
11     15      6     17     19
12      6     19      2      6
13     15     11      8      6
14     19     13     12      3
15      5      6      4      7
16     19     20      1     19
17     20     17     12      8
18     15      1     14     10

# Exercise 2 (10 points)

Data pre-processing with OOP. Create a Python class called `DataPreprocessor` that:

1. Takes a pandas DataFrame as input.
2. Provides methods to:
   - Handle missing values by filling them with the column mean.
   - Normalize numerical columns between 0 and 1.
3. Returns the cleaned DataFrame when called with `.transform()`

Consider `df` as DataFrame to test the class.

```
data = {
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "gender": ["M", "F", "M", "F", "M"]
}
df = pd.DataFrame(data)

In [72]:
import numpy as np
import pandas as pd

class DataPreprocessor:
    """Initializes the DataPreporcessor with the given Dataframe"""
    def __init__(self, df):
        self.df = df.copy()   # work on a copy so the original stays untouched
        self.num_cols = self.df.select_dtypes(include='number').columns

    def fill_missing(self):
        """Fills the missing values of a given column the datafram with the colummn mean"""
        for col in self.num_cols:
            self.df[col] = self.df[col].fillna(self.df[col].mean())
        return self

    def normalize(self):
        """Normalize the numeric columns in the datafram to the rage [0, 1]"""
        for col in self.num_cols:
            col_min = self.df[col].min()
            col_max = self.df[col].max()
            if col_max != col_min:
                self.df[col] = (self.df[col] - col_min) / (col_max - col_min)
            else:
                self.df[col] = 0.0   # avoid dividing by zero on a constant column
        return self

    def transform(self):
        self.fill_missing()
        self.normalize()
        return self.df
    
    
data = {
    "age": [25, np.nan, 35, 40, np.nan],
    "income": [50000, 60000, np.nan, 80000, 75000],
    "gender": ["M", "F", "M", "F", "M"]
}
df = pd.DataFrame(data)

print("Original:")
display(df)

preprocessor = DataPreprocessor(df)
clean_df = preprocessor.transform()

print("Cleaned:")
display(clean_df.round(4))

Original:

    age   income gender
0  25.0  50000.0      M
1   NaN  60000.0      F
2  35.0      NaN      M
3  40.0  80000.0      F
4   NaN  75000.0      M

Cleaned:

      age  income gender
0  0.0000  0.0000      M
1  0.5556  0.3333      F
2  0.6667  0.5417      M
3  1.0000  1.0000      F
4  0.5556  0.8333      M

# Exercise 3 

In this exercise, we will practice `merge` with `pandas` data frames. Merging in `pandas` is a way of combining two data frames based on a common column or set of columns. Think of it like putting together pieces of a puzzle where both tables have a shared piece of information (like a key or ID number) that helps you connect the rows that belong together.

### Exercise 3(a) (2 points)

Load the `pandas` library.

In [64]:
import pandas as pd

### Exercise 3(b) (4 points)

Create three `pandas` data-frames based on the following raw data:

```
raw_data_1 = {
        'subject_id': ['1', '2', '3', '4', '5'],
        'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'], 
        'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
        'subject_id': ['4', '5', '6', '7', '8'],
        'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'], 
        'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
        'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
        'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}
```

Call them `dat_1`, `dat_2`, and `dat_3`, respectively.

In [73]:
raw_data_1 = {
    'subject_id': ['1', '2', '3', '4', '5'],
    'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
    'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}

raw_data_2 = {
    'subject_id': ['4', '5', '6', '7', '8'],
    'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
    'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}

raw_data_3 = {
    'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
    'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

dat_1 = pd.DataFrame(raw_data_1)
dat_2 = pd.DataFrame(raw_data_2)
dat_3 = pd.DataFrame(raw_data_3)

display(dat_1, dat_2, dat_3)

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches

  subject_id first_name last_name
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

  subject_id  test_id
0          1       51
1          2       15
2          3       15
3          4       61
4          5       16
5          7       14
6          8       15
7          9        1
8         10       61
9         11       16

### Exercise 3(c) (3 points)

Combine `dat_1` and `dat_2` along the rows and call the resulting data frame `all_data`.

In [80]:
all_data = pd.concat([dat_1, dat_2])
all_data

  subject_id first_name last_name
0          1       Alex  Anderson
1          2        Amy  Ackerman
2          3      Allen       Ali
3          4      Alice      Aoni
4          5     Ayoung   Atiches
0          4      Billy    Bonder
1          5      Brian     Black
2          6       Bran   Balwner
3          7      Bryce     Brice
4          8      Betty    Btisan

### Exercise 3(d) (3 points)

Combine `dat_1` and `dat_2` along the columns and call the resulting data frame `all_data_col`.

In [81]:
all_data_col = pd.concat([dat_1, dat_2], axis=1)
all_data_col

  subject_id first_name last_name subject_id first_name last_name
0          1       Alex  Anderson          4      Billy    Bonder
1          2        Amy  Ackerman          5      Brian     Black
2          3      Allen       Ali          6       Bran   Balwner
3          4      Alice      Aoni          7      Bryce     Brice
4          5     Ayoung   Atiches          8      Betty    Btisan

### Exercise 3(e) (3 points)

Merge `all_data` and `dat_3` using `subject_id` as the key variable, and call the resulting data frame `dat_merge`.

In [83]:
dat_merge = pd.merge(all_data, dat_3, on='subject_id')
dat_merge

  subject_id first_name last_name  test_id
0          1       Alex  Anderson       51
1          2        Amy  Ackerman       15
2          3      Allen       Ali       15
3          4      Alice      Aoni       61
4          5     Ayoung   Atiches       16
5          4      Billy    Bonder       61
6          5      Brian     Black       16
7          7      Bryce     Brice       14
8          8      Betty    Btisan       15

### Exercise 3(f) (3 points)

Merge `dat_1` and `dat_2` using `subject_id` as the key variable, and call the resulting data frame `dat_merge_1`.

In [84]:
dat_merge_1 = pd.merge(dat_1, dat_2, on='subject_id')
dat_merge_1

  subject_id first_name_x last_name_x first_name_y last_name_y
0          4        Alice        Aoni        Billy      Bonder
1          5       Ayoung     Atiches        Brian       Black

### Exercise 3(g) (3 points)

Merge all the values in `dat_1` and `dat_2`, using `subject_id` as the key variable, with matching records from the left data frame. Call the resulting data frame `dat_merge_2`.

In [85]:
dat_merge_2 = pd.merge(dat_1, dat_2, on='subject_id', how='left')
dat_merge_2

  subject_id first_name_x last_name_x first_name_y last_name_y
0          1         Alex    Anderson          NaN         NaN
1          2          Amy    Ackerman          NaN         NaN
2          3        Allen         Ali          NaN         NaN
3          4        Alice        Aoni        Billy      Bonder
4          5       Ayoung     Atiches        Brian       Black

# Exercise 4

In this exercise, we will practice functional programming with `pandas` data frame. Functional programming concepts with `pandas` involves using `apply()`, `map()`, and `lambda()` functions. 

### Exercise 4(a) (3 points)

Imagine you are working with a data set of customers that includes their purchase amounts in different categories. The goal is to apply transformations and extract insights using functional programming techniques. Create the below `pandas` data frame.

```
import pandas as pd

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Groceries': [120, 150, 80, 90, 130],
    'Electronics': [200, 0, 100, 300, 150],
    'Clothing': [50, 60, 45, 70, 30]
}

df = pd.DataFrame(data)
```

In [117]:
import pandas as pd

data = {
    'Customer_ID': [101, 102, 103, 104, 105],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Groceries': [120, 150, 80, 90, 130],
    'Electronics': [200, 0, 100, 300, 150],
    'Clothing': [50, 60, 45, 70, 30]
}

df = pd.DataFrame(data)
df

   Customer_ID     Name  Groceries  Electronics  Clothing
0          101    Alice        120          200        50
1          102      Bob        150            0        60
2          103  Charlie         80          100        45
3          104    David         90          300        70
4          105      Eva        130          150        30

### Exercise 4(b) (3 points)

Use the `apply()` function to calculate the total spending for each customer (sum of `Groceries`, `Electronics`, and `Clothing`).

In [118]:
df['Total_Spending'] = df.apply(
    lambda row: row['Groceries'] + row['Electronics'] + row['Clothing'], axis=1
)
df

   Customer_ID     Name  Groceries  Electronics  Clothing  Total_Spending
0          101    Alice        120          200        50             370
1          102      Bob        150            0        60             210
2          103  Charlie         80          100        45             225
3          104    David         90          300        70             460
4          105      Eva        130          150        30             310

### Exercise 4(c) (3 points)

Use a `lambda` function to classify customers as `High`, `Medium`, or `Low` spenders based on their total spending:

- High: Total spending >= 400
- Medium: Total spending between 200 and 399
- Low: Total spending < 200

In [119]:
df['Spender_Type'] = df['Total_Spending'].apply(
    lambda x: 'High' if x >= 400 else ('Medium' if x >= 200 else 'Low')
)
df[['Name', 'Total_Spending', 'Spender_Type']]

      Name  Total_Spending Spender_Type
0    Alice             370       Medium
1      Bob             210       Medium
2  Charlie             225       Medium
3    David             460         High
4      Eva             310       Medium

### Exercise 4(d) (3 points)

Calculate the percentage of spending in `Electronics` compared to the `Total_Spend` for each customer.

In [120]:
df['Electronics_Pct'] = df.apply(
    lambda row: row['Electronics'] / row['Total_Spending'] * 100, axis=1
).round(2)
df[['Name', 'Electronics', 'Total_Spending', 'Electronics_Pct']]

      Name  Electronics  Total_Spending  Electronics_Pct
0    Alice          200             370            54.05
1      Bob            0             210             0.00
2  Charlie          100             225            44.44
3    David          300             460            65.22
4      Eva          150             310            48.39

### Exercise 4(e) (4 points)

Write a custom function that can be passed to `apply()` to give a 10% discount on electronics spending if a customer's total spend is above $400.

In [121]:
def apply_discount(row):
    if row['Total_Spending'] > 400:
        return row['Electronics'] * 0.9
    return row['Electronics']

df['Electronics_Discounted'] = df.apply(apply_discount, axis=1)
df[['Name', 'Total_Spending', 'Electronics', 'Electronics_Discounted']]

      Name  Total_Spending  Electronics  Electronics_Discounted
0    Alice             370          200                   200.0
1      Bob             210            0                     0.0
2  Charlie             225          100                   100.0
3    David             460          300                   270.0
4      Eva             310          150                   150.0